//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSenamhi.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.SenamhiSoap")]
    public interface SenamhiSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarCiudades", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListarCiudades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarCiudades", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarCiudadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarxCiudad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet listarxCiudad(string ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarxCiudad", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> listarxCiudadAsync(string ciudad);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SenamhiSoapChannel : ClienteSenamhi.ServiceReference1.SenamhiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SenamhiSoapClient : System.ServiceModel.ClientBase<ClienteSenamhi.ServiceReference1.SenamhiSoap>, ClienteSenamhi.ServiceReference1.SenamhiSoap {
        
        public SenamhiSoapClient() {
        }
        
        public SenamhiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SenamhiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SenamhiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SenamhiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ListarCiudades() {
            return base.Channel.ListarCiudades();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarCiudadesAsync() {
            return base.Channel.ListarCiudadesAsync();
        }
        
        public System.Data.DataSet listarxCiudad(string ciudad) {
            return base.Channel.listarxCiudad(ciudad);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> listarxCiudadAsync(string ciudad) {
            return base.Channel.listarxCiudadAsync(ciudad);
        }
    }
}
